---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/simecpro/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R modules $DEPLOYPATH
    - /bin/cp -R partials $DEPLOYPATH
    - /bin/cp -R sections $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp home.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
